title: "NeatStack"
email: contact@neatstack.tech
timezone: UTC
baseurl: "/affiliates-jekyll-neatstack"
permalink: "/:title/"
logo: 'assets/images/Neat Stack Logo.png'
favicon: 'assets/images/neatstack favicon.ico'
author: NeatStack Consulting Pte. Ltd.
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1
collections:
  trainings:
    output: true
    permalink: /:collection/:name/

url: "https://neatstack.com"
baseurl: ""


# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives